# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoserverPublish
                                 A QGIS plugin
 This plugin allows users to publish shapefiles in geoserver
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-07-27
        copyright            : (C) 2022 by Manoj Appalla
        email                : smappalla@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeoserverPublish class from file GeoserverPublish.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geoserverPublish import GeoserverPublish
    return GeoserverPublish(iface)
